# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1da7c6cff86bc5829de9b9f3d1bcd20ba465c27ed12641e85d24a3be98a3eb5fa6871eb13d86fdae46f7017868c69c1ac60cfc033478f3c1a092086cb32b95

test:
  secret_key_base: c3c3e59b75217e4c7d6c179ecf16b3dcf7d4bd913871155fc6de4659796142905035b1f94b55fe9f8511bb7619b1bada6e8b322c08e1f9a33e1f9568d15cf4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
